topo:
    config_path_v   : ${HEP4M_TOKENIZERS}/vqxtopox256x8x1xxxe8z5xrcs8ljleo/config_v.yml
    config_path_m   : ${HEP4M_TOKENIZERS}/vqxtopox256x8x1xxxe8z5xrcs8ljleo/config_m.yml
    checkpoint_path : ${HEP4M_TOKENIZERS}/vqxtopox256x8x1xxxe8z5xrcs8ljleo/checkpoints/epoch=50-val_total_loss=0.0000.ckpt

    codebook_loss_wts: [1, 1, 1]

track:
    config_path_v   : ${HEP4M_TOKENIZERS}/vqxtrackx256x8x1xxx1tkosl645s31y/config_v.yml
    config_path_m   : ${HEP4M_TOKENIZERS}/vqxtrackx256x8x1xxx1tkosl645s31y/config_m.yml
    checkpoint_path : ${HEP4M_TOKENIZERS}/vqxtrackx256x8x1xxx1tkosl645s31y/checkpoints/epoch=49-val_total_loss=0.0000.ckpt

    codebook_loss_wts: [1, 1, 1]

truthpart:
    config_path_v   : ${HEP4M_TOKENIZERS}/vqxtrpartx128x8x1xxx3hty86rc6e3c/config_v.yml
    config_path_m   : ${HEP4M_TOKENIZERS}/vqxtrpartx128x8x1xxx3hty86rc6e3c/config_m.yml
    checkpoint_path : ${HEP4M_TOKENIZERS}/vqxtrpartx128x8x1xxx3hty86rc6e3c/checkpoints/epoch=50-val_total_loss=0.0000.ckpt

    codebook_loss_wts: [1, 1, 1]

hgpfpart:
    config_path_v   : ${HEP4M_TOKENIZERS}/vqxhgpartx128x8x2xxxtsgcse59z19u/config_v.yml
    config_path_m   : ${HEP4M_TOKENIZERS}/vqxhgpartx128x8x2xxxtsgcse59z19u/config_m.yml
    checkpoint_path : ${HEP4M_TOKENIZERS}/vqxhgpartx128x8x2xxxtsgcse59z19u/checkpoints/epoch=50-val_total_loss=0.0000.ckpt

    codebook_loss_wts: [1, 1, 1]

cell:
    config_path_v   : ${HEP4M_TOKENIZERS}/vqxcellx2048x8xq3x2xxxli0k2qgzx8/config_v.yml
    config_path_m   : ${HEP4M_TOKENIZERS}/vqxcellx2048x8xq3x2xxxli0k2qgzx8/config_m.yml
    checkpoint_path : ${HEP4M_TOKENIZERS}/vqxcellx2048x8xq3x2xxxli0k2qgzx8/checkpoints/epoch=50-val_total_loss=0.0003.ckpt

    codebook_loss_wts: [1, 1, 1]

celltruth:
    config_path_v   : ${HEP4M_TOKENIZERS}/vqxcelltrx2048x8xq3x2xxxxt0u78n6/config_v.yml
    config_path_m   : ${HEP4M_TOKENIZERS}/vqxcelltrx2048x8xq3x2xxxxt0u78n6/config_m.yml
    checkpoint_path : ${HEP4M_TOKENIZERS}/vqxcelltrx2048x8xq3x2xxxxt0u78n6/checkpoints/epoch=50-val_total_loss=0.0035.ckpt

    codebook_loss_wts: [1, 1, 1]

truthjet:
    config_path_v   : ${HEP4M_TOKENIZERS}/vqxtrjetx128x8x1xxx7vuko2docw4ie/config_v.yml
    config_path_m   : ${HEP4M_TOKENIZERS}/vqxtrjetx128x8x1xxx7vuko2docw4ie/config_m.yml
    checkpoint_path : ${HEP4M_TOKENIZERS}/vqxtrjetx128x8x1xxx7vuko2docw4ie/checkpoints/epoch=48-val_total_loss=0.0013.ckpt

    codebook_loss_wts: [1]